apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-jeager
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
spec:
  selector:
    matchLabels:
      app: auth-service-jeager
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service-jeager
    spec:
      containers:
        - name: auth-service-jeager
          image: uk.icr.io/ix-liberty-rhg/auth-service
          env:
            - name: EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: expiration
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: apiKey
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: secretKey
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: bucketName
            - name: ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: endpointURL
            - name: IAM_ENPOINT
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: iamEndpoint
            - name: LOCATION
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-auth
                  key: location
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-jeager
spec:
  selector:
    app: auth-service-jeager
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort